# application-prod.properties
spring.datasource.url=jdbc:postgresql://<tu-host>.neon.tech/<tu-db>
spring.datasource.username=<tu-usuario>
spring.datasource.password=<tu-password>
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true